# This file is for the labeler workflow
# Documentation https://github.com/marketplace/actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file: [docs/**, "./*.{md,mdx}"]

tests:
  - changed-files:
      - any-glob-to-any-file: [tests/**, ./*test*]

ci:
  - changed-files:
      - any-glob-to-any-file: [.github/workflows/**]

server:
  - changed-files:
      - any-glob-to-any-file: [server/**]

client:
  - changed-files:
      - any-glob-to-any-file: [client/**]

parser:
  - changed-files:
      - any-glob-to-any-file: [parser/**]
