services:
  client:
    container_name: sharkalyze-client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
    develop:
      watch:
        - path: client
          action: rebuild

  server:
    container_name: sharkalyze-server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 3000:3000
    develop:
      watch:
        - path: server/src
          action: rebuild

        - path: poetry.lock
          action: rebuild
