name: Linting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          set -xe
          make install/python

      - name: Lint with ruff
        run: |
          set -xe
          make lint/python
  npm:
    name: NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          set -xe
          make install/npm

      - name: Lint
        run: |
          set -xe
          make lint/npm

  # TODO: Rust

  check:
    if: always()
    name: Linting Successful
    runs-on: ubuntu-latest
    needs: [python, npm]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
