name: Run Test Suite

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  python-test:
    name: Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          set -xe
          echo "Installed dependencies"
          make install/python

      - name: Testing
        run: |
          set -xe
          make test/python

  server-build:
    name: Python build
    runs-on: ubuntu-latest
    needs: [python-test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -xe
          docker build . -f server/Dockerfile

  client-test:
    name: Node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          set -xe
          make install/npm

      - name: Testing
        run: |
          set -xe
          make test/npm

  client-build:
    name: Node build
    runs-on: ubuntu-latest
    needs: [client-test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -xe
          docker build . -f client/Dockerfile

  # TODO: Rust

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [python-test, client-test, client-build, server-build]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
