name: Run Test Suite

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  changed-files:
    name: Changed Files
    runs-on: ubuntu-latest
    outputs:
      server-test: ${{ steps.changed-files.outputs.server-test_any_modified == 'true' }}
      npm-test: ${{ steps.changed-files.outputs.npm-test_any_modified == 'true' }}
      rust: ${{ steps.changed-files.outputs.rust_any_modified == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits

      - name: Find changed files
        uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files_yaml: |
            common: &common
              - .github/workflows/test-worker.yml
              - Makefile

            rust:
              - *common
              - parser/**
              - Cargo.toml
              - Cargo.lock

            server-test:
              - *common
              - server/**
              - poetry.lock
              - pyproject.toml

            npm-test:
              - *common
              - client/**

  server-test:
    name: Server
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.server-test == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          set -xe
          echo "Installed dependencies"
          make install/python

      - name: Testing
        run: |
          set -xe
          make test/python

  client-test:
    name: Node
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.client-test == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          set -xe
          make install/npm

      - name: Testing
        run: |
          set -xe
          make test/npm

  rust:
    name: Rust
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.rust == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          set -xe
          rustup update stable
          rustup default stable

      - name: Build
        run: |
          set -xe
          cargo build --verbose

      - name: Test
        run: |
          set -xe
          cargo test --verbose

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [server-test, client-test, rust]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}
